/** @type {import('tailwindcss').Config} */
export default {
  darkMode: 'class',
  content: ['./index.html', './src/**/*.{js,jsx}'],
  theme: {
    extend: {
      colors: {
        'primary-fixed': '#d2e4ff',
        'on-tertiary-fixed': '#2a1700',
        primary: '#000917',
        background: '#f8f9ff',
        'surface-container-highest': '#d3e4fe',
        'on-primary-fixed-variant': '#364860',
        'on-surface-variant': '#44474d',
        'on-tertiary-container': '#bd7800',
        'outline-variant': '#c4c6cd',
        'surface-bright': '#f8f9ff',
        'surface-tint': '#4d6079',
        'inverse-primary': '#b5c8e5',
        'tertiary-container': '#301b00',
        'inverse-on-surface': '#eaf1ff',
        'on-secondary-container': '#fefcff',
        'on-background': '#0b1c30',
        'tertiary-fixed-dim': '#ffb95f',
        'on-primary-container': '#7689a4',
        'on-tertiary-fixed-variant': '#653e00',
        tertiary: '#100600',
        surface: '#f8f9ff',
        'on-error-container': '#93000a',
        'on-secondary': '#ffffff',
        secondary: '#0051d5',
        'on-secondary-fixed-variant': '#003ea8',
        'on-primary': '#ffffff',
        'inverse-surface': '#213145',
        'surface-container': '#e5eeff',
        'surface-container-lowest': '#ffffff',
        'surface-container-high': '#dce9ff',
        'tertiary-fixed': '#ffddb8',
        'primary-fixed-dim': '#b5c8e5',
        'on-tertiary': '#ffffff',
        'secondary-fixed': '#dbe1ff',
        'primary-container': '#0d2137',
        'surface-dim': '#cbdbf5',
        'surface-variant': '#d3e4fe',
        error: '#ba1a1a',
        'on-secondary-fixed': '#00174b',
        'on-surface': '#0b1c30',
        'on-error': '#ffffff',
        'surface-container-low': '#eff4ff',
        'secondary-fixed-dim': '#b4c5ff',
        outline: '#74777d',
        'error-container': '#ffdad6',
        'on-primary-fixed': '#081c32',
        'secondary-container': '#316bf3',
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg: '0.5rem',
        xl: '0.75rem',
        '2xl': '1rem',
        '3xl': '1.5rem',
        full: '9999px',
      },
      spacing: {
        gutter: '1.5rem',
        'space-md': '1rem',
        margin: '3rem',
        'space-sm': '0.5rem',
        'margin-mobile': '1.25rem',
        'space-lg': '1.5rem',
        'gutter-mobile': '1rem',
        'space-xl': '2.5rem',
        'space-xs': '0.25rem',
      },
      fontFamily: {
        'headline': ['Plus Jakarta Sans', 'sans-serif'],
        'body': ['Inter', 'sans-serif'],
        'label': ['Plus Jakarta Sans', 'sans-serif'],
      },
      fontSize: {
        'headline-sm': ['18px', { lineHeight: '26px', letterSpacing: '-0.005em', fontWeight: '600' }],
        'display-md': ['44px', { lineHeight: '52px', letterSpacing: '-0.025em', fontWeight: '700' }],
        'body-lg': ['16px', { lineHeight: '26px', letterSpacing: '0em', fontWeight: '400' }],
        'label-sm': ['11px', { lineHeight: '14px', letterSpacing: '0.04em', fontWeight: '700' }],
        'headline-lg': ['28px', { lineHeight: '36px', letterSpacing: '-0.015em', fontWeight: '700' }],
        'label-lg': ['14px', { lineHeight: '20px', letterSpacing: '0.01em', fontWeight: '600' }],
        'display-md-mobile': ['32px', { lineHeight: '40px', letterSpacing: '-0.02em', fontWeight: '700' }],
        'display-lg': ['56px', { lineHeight: '64px', letterSpacing: '-0.03em', fontWeight: '800' }],
        'label-md': ['12px', { lineHeight: '16px', letterSpacing: '0.02em', fontWeight: '600' }],
        'display-lg-mobile': ['38px', { lineHeight: '46px', letterSpacing: '-0.025em', fontWeight: '800' }],
        'body-xl': ['18px', { lineHeight: '28px', letterSpacing: '-0.005em', fontWeight: '400' }],
        'body-md': ['14px', { lineHeight: '22px', letterSpacing: '0em', fontWeight: '400' }],
        'body-sm': ['12px', { lineHeight: '18px', letterSpacing: '0.01em', fontWeight: '400' }],
        'headline-xl': ['36px', { lineHeight: '44px', letterSpacing: '-0.02em', fontWeight: '700' }],
        'headline-md': ['22px', { lineHeight: '30px', letterSpacing: '-0.01em', fontWeight: '600' }],
        'headline-xl-mobile': ['28px', { lineHeight: '36px', letterSpacing: '-0.015em', fontWeight: '700' }],
      },
    },
  },
  plugins: [],
};

